openapi: 3.0.0
info:
  title: GameService.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/game/{id}/exists':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Gets whether the game with the given ID exists
      tags:
        - game
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      operationId: get-game-id-exists
  '/game/{type}':
    post:
      summary: Create Game
      operationId: create-game
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Creates a new game of the specified type
      tags:
        - game
    parameters:
      - schema:
          type: string
        name: type
        in: path
        required: true
  /game-types:
    get:
      summary: Gets the game types the server supports
      tags:
        - game
      responses:
        '200':
          description: List of game types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GameType'
      operationId: get-game-types
components:
  schemas:
    GameType:
      title: GameType
      type: object
      properties:
        iconUrl:
          type: string
          format: uri
        displayName:
          type: string
        gameType:
          type: string
      required:
        - iconUrl
        - displayName
        - gameType
